### ISSUE TITLE
Website inaccessible over https

### ISSUE THREAD

**Issue by brahma-dev** [abhinav-upadhyay/apropos_web#3]

**Comment by abhinav-upadhyay** [comment]
Thanks for the issue. I recently migrated the server from a Linux OS to NetBSD-7. Unfortunately the Lets Encrypt client (certbot) seems to be crashing on NetBSD-7. I am trying to figure it out in order to generate the certificates. Till then it's HTTP only :(

**Comment by abhinav-upadhyay** [comment]
Fixed (moved back to a Linux server)
