### ISSUE TITLE
Search for "progname" yields broken result

### ISSUE THREAD

**Issue by jlmuir** [abhinav-upadhyay/apropos_web#5]
I searched for "progname" (without the double-quotes) at https://man-k.org/ on the "NetBSD-current" set and got a long garbled result of escaped HTML, the first ten lines of which look like:

```
progname(?) one line about what it does a one line description
</pre> </div> <div class="Pp"></div> Multiple &#8216;Nm&#8217;
names should be separated by commas. <div class="Pp"></div> The <a
class="Sx" href="#Nm">Nm</a> macro(s) must precede the <a class="Sx"
href="#Nd">Nd</a> macro. <div class="Pp"></div> See <a class="Sx"
href="#Nm">Nm</a> and <a class="Sx" href="#Nd">Nd</a>.</dd> <dt
class="It-ohang"><i class="Em">LIBRARY</i></dt> <dd class="It-ohang">The
name of the library containing the documented material, which is
assumed to be a function in a section 2, 3, or 9 manual. The syntax
for this is as follows: <div class="Pp"></div> <div class="Bd"
```

**Comment by abhinav-upadhyay** [comment]
Thank you for reporting it, I am looking into it. Looks like the HTML template is being sent as it is without populating the results (possibly because of some sort of exception)

**Comment by abhinav-upadhyay** [comment]
Just fixed it, it was caused because of version mismatch of the mandoc library and apropos code. Thanks for pointing it out.
